title: "Cringe ass naenae baby"
author: "Robin/Milieu"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "archive.html"}
  - {file: "comp.html"}
  - {file: "ling.html"}
  - {file: "phil.html"}
  #- {title: "Professional"}
  #- {url: "cv.html"}
  #- {url: "projects.html"}
  #- {url: "bio.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter, icon: twitter-square, url: "https://twitter.com/politbuwu"}
  - {title: Mail, icon: envelope, url: "https://robincrofts112@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/milberry"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
